// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAln6QFOwjeQJD_Av1TW0WYkGjNzuefJWM',
    appId: '1:235239035722:android:1618bf48d52b0b2638e7b3',
    messagingSenderId: '235239035722',
    projectId: 'market-7810a',
    storageBucket: 'market-7810a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc2ijcH0D8T0x7xWhwqE7_WHj1aLt8hjA',
    appId: '1:235239035722:ios:65b29f0f94f10a2238e7b3',
    messagingSenderId: '235239035722',
    projectId: 'market-7810a',
    storageBucket: 'market-7810a.firebasestorage.app',
    iosBundleId: 'com.example.market',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFlR54j2yfLVNe8JQM9Mvo7bT0xaoUkNY',
    appId: '1:235239035722:web:9c3134fc8474678838e7b3',
    messagingSenderId: '235239035722',
    projectId: 'market-7810a',
    authDomain: 'market-7810a.firebaseapp.com',
    storageBucket: 'market-7810a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc2ijcH0D8T0x7xWhwqE7_WHj1aLt8hjA',
    appId: '1:235239035722:ios:65b29f0f94f10a2238e7b3',
    messagingSenderId: '235239035722',
    projectId: 'market-7810a',
    storageBucket: 'market-7810a.firebasestorage.app',
    iosBundleId: 'com.example.market',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFlR54j2yfLVNe8JQM9Mvo7bT0xaoUkNY',
    appId: '1:235239035722:web:a3b8f4f6fb421f4338e7b3',
    messagingSenderId: '235239035722',
    projectId: 'market-7810a',
    authDomain: 'market-7810a.firebaseapp.com',
    storageBucket: 'market-7810a.firebasestorage.app',
  );

}